on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        id: git-tag
        run: echo "Works. Tag is ${GITHUB_REF##*/}"

