name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: echo "Works. Tag is ${GITHUB_REF##*/}"
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
