on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prueba
        run: git fetch --prune --unshallow --tags
      - name: Get version and tag
        run:  echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV
      - name: Get tag
        id: tag
       # uses: dawidd6/action-get-tag@v1
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
