name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: versiones tag
        run: git fetch --prune --unshallow --tags
      - name: nada
        run: echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV
      - name: Debug
        run: echo "Works. Tag is ${GITHUB_REF##*/}"

