name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
   unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        env:
          GITHUB_USERNAME: ${{ secrets.USER_NAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: mvn --batch-mode test
   build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: mvn clean install -DskipTests=true
      - name: Lista
        run: ls -la
