name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: versiones tag
        run: git fetch --prune --unshallow --tags
      - name: nada
        id: tag3
        run: echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" 
      - name: Debug
        env:
         IMAGE_TAG2: ${steps.tag3.outputs.LATEST_TAG}}
        run: echo "Works. Tag is ${GITHUB_REF##*/}"
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
    
      - name: Configure AWS Credentials for build and deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
          aws-region: us-east-2        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: squad-integration 
          IMAGE_TAG: ${{steps.tag2.outputs.tag2}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

