on:
  push:
    branches:
      - main # or the name of your main branch
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prueba
        run: git fetch --prune --unshallow
      - name: Get version and tag
        run: |
            echo "CURRENT_VERSION=$version" >> $GITHUB_ENV
            echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV
