name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        #run: mvn --settings settings.xml clean test
        run: mvn clean install package
