name: Pull-azure
on:
 push:
   branches:
      - main # or the name of your main branch
      
jobs:  
  push_azure:
    runs-on: ubuntu-latest
    steps:
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      env:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        docker login $AZURE_REGISTRY_LOGIN_SERVER -u $AZURE_REGISTRY_USERNAME -p $AZURE_REGISTRY_PASSWORD
   #    docker images
   #     docker images azacreu2ossd01.azurecr.io
   #     az acr repository list -n azacreu2ossd01.azurecr.io
   #     azure aks list-images --repository-name $AZURE_REGISTRY_LOGIN_SERVER
   #    docker build . -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
