name: Pull-azure
on:
 push:
   branches:
      - main # or the name of your main branch
      
jobs:  

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: versiones tag
        run: git fetch --prune --unshallow --tags
      - name: latest tag
        run: echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV
      - name: use env var
        run: echo ${{ env.LATEST_TAG }}

      - name: Configure AWS Credentials for build and deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
          aws-region: us-east-2        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: squad-integration 
          IMAGE_TAG: ${{env.LATEST_TAG}}
        run:  |
          aws ecr list-images --repository-name $ECR_REPOSITORY
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:loadflow$IMAGE_TAG
      - name: docker images
        run: docker images
 
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} 
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }} 
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}         
      - name: ecr 2 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: squad-integration 
          IMAGE_TAG: ${{env.LATEST_TAG}}
        run: |     
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:loadflow$IMAGE_TAG azacreu2ossd01.azurecr.io/$ECR_REGISTRY/$ECR_REPOSITORY:loadflow$IMAGE_TAG
          docker images
          docker push azacreu2ossd01.azurecr.io/$ECR_REGISTRY/$ECR_REPOSITORY:loadflow$IMAGE_TAG
