name: Pull-azure
on:
  push:
    branches:
      - main # or the name of your main branch
      
jobs: 
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials for build and deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
          aws-region: us-east-2  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: ecr 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: squad-integration    
        run:  |
          aws ecr list-images --repository-name $ECR_REPOSITORY
   #       docker pull $ECR_REGISTRY/$ECR_REPOSITORY:1.7
      - name: docker images
        run: docker images
    
  push_azure:
    runs-on: ubuntu-latest
    needs: [build-artifact]
    steps:
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        az acr repository list --name $login-server --output table
   #     azure aks list-images --repository-name $AZURE_REGISTRY_LOGIN_SERVER
   #    docker build . -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
